### PR TITLE
UMD taken

### PR DESCRIPTION
**Pull request by recca0120**

### CODE REVIEW

**Comment by jcubic** [comment]
sorry, but this PR make no sense. You've added comment that just wrong and you've broken the code

**Comment by jcubic** [comment]
In 84b6081 I've added UMD for unix_formatting.js

**Comment by recca0120** [comment]
Hi. @jcubic 

it's so wired , I want to do this
https://github.com/recca0120/laravel-terminal/blob/master/resources/assets/ts/unix_formatting.js
but this pr ...

anyway. thanks for your help ...

**Comment by jcubic** [comment]
In you're PR you didn't added the actual UMD. look at the diff. Maybe you commited and pushed the code and didn't save the file.

**Comment by recca0120** [comment]
Yes.

it's my fault. XDD

**Pull request closed without merging**
