### PR TITLE
Fix for #3 Firefox MacOS paste problem

### PR DESCRIPTION
**Pull request by stereobooster**

### CODE REVIEW

**Comment by jcubic** [comment]
Sorry to bothering you again but can you modify `-src.js`? the 1.0.6 will be overwritten by make.

**Comment by jcubic** [comment]
I can add that fix myself but since you came up with fix you should be on the list of contributors on github.

**Comment by stereobooster** [comment]
I've been told this change breaks some things. I tested it only in firefox, though

>This breaks the TAB-completion on safari as well as the Backspace key. On chrome it looks that with C-c / C -v pastes twice...

**Comment by jcubic** [comment]
Unfortunetly I don't have a Mac, can you test this [codepen](http://codepen.io/jcubic/pen/ygWomg) on a Mac, for the backspace and TAB and tell me what the results are?

As for C-v it was broken in all browsers, it should work again now.

**Comment by jcubic** [comment]
Tested in VirutalBox and Tab Backspace and paste work.

**Pull request merged**
