### PR TITLE
fix: typing of terminalObjectFunction (this)

### PR DESCRIPTION
**Pull request by antoineol**
The PR instructions say to make the PR against the devel branch, but that branch seems behind master. I was thinking it would be simpler for you to target master for the merge :)

This PR is a super simple change in a typing, not to have typing errors in the hello world example from [this article](https://itnext.io/how-to-create-interactive-terminal-like-website-888bb0972288) (type `this`).

### CODE REVIEW

**Comment by jcubic** [comment]
Thanks for the fix, it seems that I've forget the type for this in this particular type.

But please use devel branch. It will help me know that there are things to be released. I've update devel branch when I get back home. I forget to update it after merging devel to master before the release.

**Comment by jcubic** [comment]
Also there is a file that test the types can, it also need to updated for instance to call this.echo in object interpreter.

**Comment by antoineol** [comment]
I've added a test and the tsconfig flag that reveals the error. I would recommend `strict: true` instead, but it adds many more TS errors I don't have time to fix now :)

For the sake of keeping the current PR (instead of opening a new one), you will see the changes in the source repo (fork) in master branch, but I have force put it at the `devel` commit, so the diff should be good to merge the PR.

**Comment by jcubic** [comment]
Thanks for the fix

**Comment by antoineol** [comment]
Btw I haven't said earlier, but thank to you, first, for this amazing library! It's the simplest way I have found to code a fake terminal 👍

**Comment by jcubic** [comment]
I have no idea why but tests failed after merging. I need to investigate. Just found it now.

**Pull request merged**
